development:
  adapter: postgresql
  database: new_auth_demo_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: new_auth_demo_test
  host: localhost
  pool: 5
  timeout: 5000